name: Deploy rust.leix.wang website
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install
        npm run-script build
        cd ./markdown/.vitepress/dist
        echo 'rust.leix.wang' > CNAME
        git init
        git config user.name "Rust"
        git config user.email "ruest@leix.wang"
        git add -A
        git commit -m 'deploy'
        git push -f https://leixwang:${{ secrets.BUILD_LEIXWEB }}@github.com/leixwang/rust.github.io.git master:gh-pages
        cd -